apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-dk2h
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vrka-tenant/rhtap-demo-app/hacbs-test-project-dk2h@sha256:d0d2769e04a74364b61ddcdb4fd67913a8c9c46708b7cb8f7570af79c593b90d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
