apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-dk2h
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vrka-tenant/rhtap-demo-app/hacbs-test-project-dk2h@sha256:69b89f9ac14f9f75418fb09efaa783bafb976c35ea0e7775a427fa9e1edc765d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
